version: '3'

services:
  db:
    image: postgres
    volumes:
      - postgres_data:/var/lib/postgresl/data/
    environment:
      POSTGRES_USER: dev
      POSTGRES_DB: dev
      POSTGRES_PASSWORD: ""
  web:
     build: .
#     entrypoint: ["sh", "-c", "sleep infinity"]
     command: python manage.py migrate --noinput
     command: python manage.py runserver 0.0.0.0:8000
     volumes:
       - .:/code
     ports:
       - "8000:8000"
     depends_on:
       - db
     environment:
       DATABASE_URL: postgresql://dev:@db/dev
  form:
    image: node:9-stretch
    working_dir: /app
    ports:
      - "9000:9000"
    command: bash -c "yarn install && yarn run develop"
    links:
      - db
      - web
    volumes:
      - ./form:/app
    tty: true

volumes:
  postgres_data: